rootProject.name = "Vulpecula"

include("common-applicative")
include("common-config")
include("common-core")
include("common-diagram")

include("extension-anser")

include("module-action-entity")
include("module-action-event")
include("module-action-illusion")
include("module-action-item")
include("module-action-memory")
include("module-action-target")
include("module-anser")
include("module-bacikal")
include("module-command")
include("module-core")
include("module-dispatcher")
include("module-experiment")
include("module-property-entity")
include("module-schedule")
include("module-script")
include("module-updater")
include("module-volatility")
include("module-wireshark")

include("platform-bukkit")
include("plugin-snapshot")

include("workflow-action")
include("workflow-build")
include("workflow-metadata")
include("workflow-property")
include("workflow-resources")