plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
rootProject.name="Vulpecula"
include("common-applicative")
include("common-config")
include("common-core")
include("extension-action-item")
include("module-bacikal")
include("module-command")
include("module-core")
include("module-dispatcher")
include("module-dispatcher-legacy")
include("module-experiment")
include("module-item")
include("module-item-test")
include("module-schedule")
include("module-script")
include("module-wireshark")
include("platform-bukkit")
include("plugin-mini")

include("project:common")
include("project:common-core")
include("project:common-legacy")
include("project:extension-anser")
include("project:module-applicative")
include("project:module-bacikal")
include("project:module-config")
include("project:module-volatile")
include("common-lang")
