
# Bacikal.Registry.Config

actions: {
    item: {
        local: [
            "vulpecula:item"
        ]
        remote: [
            "vulpecula:item"
        ]
    }
    test: {
        local: [
            "vulpecula:test"
        ]
        remote: [
            "vulpecula:test"
        ]
    }
}